webserver/clothatar/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'clothatar'

urlpatterns = [
    # clothmatch/query
    url(r'^$', views.cloth_list, name='cloth_list'),
    url(r'^user_login$', views.user_login, name='user_login'),
    url(r'^user_logout$', views.user_logout, name='user_logout'),
    url(r'^detail/(?P<family_id>\d)$', views.cloth_detail, name='cloth_detail'),
    url(r'^query$', views.match_query, name='query')
]

webserver/webserver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^clothatar/', include('clothatar.urls')),
    url(r'^$', include('clothatar.urls'))
]

webserver/clothatar/models.py
from django.db import models

# Create your models here.


class Clothing(models.Model):
    clothing_id = models.AutoField(primary_key=True)
    # family = models.ForeignKey('ClothingFamily', models.DO_NOTHING, blank=True, null=True)
    family_id = models.IntegerField(unique=True, blank=True, null=True)
    avatar_id = models.IntegerField(unique=True, blank=True, null=True)
    clothing_size = models.ForeignKey('ClothingSizes', models.DO_NOTHING, db_column='clothing_size', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    head_to_foot_weight = models.FloatField(blank=True, null=True)
    bust_weight = models.FloatField(blank=True, null=True)
    waist_weight = models.FloatField(blank=True, null=True)
    hips_weight = models.FloatField(blank=True, null=True)
    neck_to_wrist_bent_weight = models.FloatField(blank=True, null=True)
    inside_neck_to_waist_weight = models.FloatField(blank=True, null=True)
    waist_to_ankle_weight = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clothing'

    def __str__(self):
        return "{}--{}--{}--{}--{}".format(self.clothing_id,
                                           self.family_id,
                                           self.avatar_id,
                                           self.clothing_size,
                                           self.description)


class ClothingAvatar(models.Model):
    # avatar = models.ForeignKey(Clothing, models.DO_NOTHING, primary_key=True)
    avatar_id = models.IntegerField(primary_key=True)
    head_to_foot = models.FloatField(blank=True, null=True)
    bust = models.FloatField(blank=True, null=True)
    waist = models.FloatField(blank=True, null=True)
    hips = models.FloatField(blank=True, null=True)
    neck_to_wrist_bent = models.FloatField(blank=True, null=True)
    inside_neck_to_waist = models.FloatField(blank=True, null=True)
    waist_to_ankle = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clothing_avatar'

    def __str__(self):
        return '{}__{}__{}__{}__{}__{}__{}__{}'.format(self.avatar_id,
                                                       self.head_to_foot,
                                                       self.bust,
                                                       self.waist,
                                                       self.hips,
                                                       self.neck_to_wrist_bent,
                                                       self.inside_neck_to_waist,
                                                       self.waist_to_ankle)


class ClothingFamily(models.Model):
    family_id = models.AutoField(primary_key=True)
    description = models.TextField(blank=True, null=True)
    manufacturer = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clothing_family'


class ClothingSizes(models.Model):
    size_id = models.AutoField(primary_key=True)
    size_desc = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'clothing_sizes'

    def __str__(self):
        return "{}--{}".format(self.size_id, self.size_desc)


class Person(models.Model):
    person_id = models.AutoField(primary_key=True)
    avatar_id = models.IntegerField(unique=True, blank=True, null=True)
    name = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'person'

    def __str__(self):
        return "{}--{}--{}".format(self.person_id, self.avatar_id, self.name)


class PersonAvatar(models.Model):
    # avatar = models.ForeignKey(Person, models.DO_NOTHING, primary_key=True)
    avatar_id = models.IntegerField(primary_key=True)
    head_to_foot = models.FloatField(blank=True, null=True)
    bust = models.FloatField(blank=True, null=True)
    waist = models.FloatField(blank=True, null=True)
    hips = models.FloatField(blank=True, null=True)
    neck_to_wrist_bent = models.FloatField(blank=True, null=True)
    inside_neck_to_waist = models.FloatField(blank=True, null=True)
    waist_to_ankle = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'person_avatar'

    def __str__(self):
        return "{}--{}--{}--{}--{}--{}--{}--{}".format(self.avatar_id,
                                                       self.head_to_foot,
                                                       self.bust,
                                                       self.waist,
                                                       self.hips,
                                                       self.neck_to_wrist_bent,
                                                       self.inside_neck_to_waist,
                                                       self.waist_to_ankle)

webserver/clothatar/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from django.http import HttpResponse
from django.http import JsonResponse


from .models import Person
from .models import PersonAvatar
from .models import Clothing
from .models import ClothingAvatar
from .models import ClothingFamily
# Create your views here.


@login_required(login_url='/admin/login/')
def user_login(request):
    # return HttpResponse('You have login')
    return redirect('/clothatar')


def user_logout(request):
    logout(request)
    return redirect('/clothatar')
    # return HttpResponse('You have logout')


def cloth_list(request):
    user_name = 'None'
    if not request.user.is_authenticated:
        user_login = 0
    else:
        user_login = 1
        user_name = request.user.username

    if user_name == 'anna':
        customer_id = 1

    clothings = []

    clothings.append({'pic_name': 'img/p-1-1.jpg', 'match_point': 98, 'size': 'AU 10', 'description': 'Elise Ruffle Wrap Dress atmos', 'family_id': 1, 'price': 24.99})
    clothings.append({'pic_name': 'img/p-2-1.jpg', 'match_point': 100, 'size': 'AU 10', 'description': 'Palm Springs Drape Dress Cooper St', 'family_id': 2, 'price': 32.99})
    clothings.append({'pic_name': 'img/p-3-1.jpg', 'match_point': 99, 'size': 'AU 10', 'description': 'Monet Dress Fresh Soul', 'family_id': 3, 'price': 55.99})

    context = {'user_login': user_login, 'clothings': clothings}

    return render(request, 'clothatar/list.html', context)


def cloth_detail(request, family_id):
    user_name = 'None'
    customer_id = 0
    if not request.user.is_authenticated:
        user_login = 0
    else:
        user_login = 1
        user_name = request.user.username

    if user_name == 'anna':
        customer_id = 1

    pic_name = 'img/p-{}-1.jpg'.format(family_id)

    match_result = match_cloth(customer_id, family_id)

    context = {'pic_name': pic_name, 'user_login': user_login, 'match_result': match_result}

    print("context--->:", context)

    return render(request, 'clothatar/details.html', context)


def match_cloth(customer_id, family_id):
    query_result = {}
    clothings = []

    query_result['customer_id'] = customer_id
    query_result['clothings'] = clothings

    if customer_id > 0:
        people = Person.objects.filter(person_id=customer_id)[0]
        people_avatar = PersonAvatar.objects.filter(avatar_id=people.avatar_id)[0]
    else:
        people = None
        people_avatar = None

    clothing_family = ClothingFamily.objects.filter(family_id=family_id)[0]

    query_result['description'] = clothing_family.description
    clothings_set = Clothing.objects.filter(family_id=family_id)

    min_value = 10000
    suggest_size = 'unknown'

    for cloth in clothings_set:
        cloth_avatar_set = ClothingAvatar.objects.filter(avatar_id=cloth.avatar_id)

        if cloth_avatar_set is not None:
            cloth_avatar = cloth_avatar_set[0]
            print('cloth_avatar--->:', cloth_avatar)

            match_info = {}

            match_info['id'] = cloth_avatar.avatar_id
            match_info['match_point'] = 0
            match_info['size'] = cloth.clothing_size.size_desc

            if people_avatar is not None:
                match_info['waist'] = people_avatar.waist - cloth_avatar.waist
                match_info['hips'] = people_avatar.hips - cloth_avatar.hips
                match_info['bust'] = people_avatar.bust - cloth_avatar.bust

                v1 = sum([abs(match_info['waist']), abs(match_info['hips']), abs(match_info['bust'])])
                if min_value > v1:
                    min_value = v1
                    suggest_size = cloth.clothing_size.size_desc

                avg_value = int(v1 / len([match_info['waist'], match_info['hips'], match_info['bust']]))
                match_info['match_point'] = 100 - avg_value

                print("avg_value--->", avg_value)
                print("match_point--->", match_info['match_point'])

            else:
                match_info['waist'] = cloth_avatar.waist
                match_info['hips'] = cloth_avatar.hips
                match_info['bust'] = cloth_avatar.bust

            clothings.append(match_info)

    query_result['suggest_size'] = suggest_size

    print("suggest_size--->", suggest_size)

    # print("return resutl --->: ", query_result)
    return query_result


def match_query(request):

    post_content = request.POST

    # print("request --->", request)
    # print("request msg--->", post_content)
    # customer_id = int(post_content['customer_id'])
    # clothing_id_list = post_content.getlist('clothing')

    # print('customer_id -->', customer_id)
    # print('clothing_id_list -->', clothing_id_list, type(clothing_id_list))

    query_result = {}
    clothings = []

    # people_avatar_id = 1

    customer_id = 1
    family_id = 1

    query_result['customer_id'] = customer_id
    query_result['clothings'] = clothings

    people = Person.objects.filter(person_id=customer_id)[0]

    # people_avatar = PersonAvatar.objects.filter(avatar__avatar_id=people.avatar_id)

    people_avatar = PersonAvatar.objects.filter(avatar_id=people.avatar_id)[0]

    # print('people--->', people)

    # for pa in people_avatars:
    #     print('pa--->', pa)

    # print('people_avatar--->', people_avatar)

    clothings_set = Clothing.objects.filter(family_id=family_id)

    for cloth in clothings_set:
        cloth_avatar_set = ClothingAvatar.objects.filter(avatar_id=cloth.avatar_id)

        if cloth_avatar_set is not None:
            cloth_avatar = cloth_avatar_set[0]
            print('cloth_avatar--->:', cloth_avatar)

            match_info = {}

            match_info['id'] = cloth_avatar.avatar_id
            match_info['match_point'] = 98
            match_info['size'] = cloth.clothing_size.size_desc
            match_info['waist'] = people_avatar.waist - cloth_avatar.waist
            match_info['hips'] = people_avatar.hips - cloth_avatar.hips
            match_info['bust'] = people_avatar.bust - cloth_avatar.bust

            clothings.append(match_info)

    print("return resutl --->: ", query_result)
    return JsonResponse(query_result)

webserver/clothatar/templates/clothatar/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" type="text/css" href="{% static 'css/clothatar.css' %}">

</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Clothatar Powered</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="{%url 'clothatar:cloth_list'%}">Home</a></li>
      {% if user_login == 1 %}
      <li><a href="{%url 'clothatar:user_logout'%}">Logout</a></li>
      {% else %}
      <li><a href="{%url 'clothatar:user_login'%}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>


<div class="container">
      {% block content %}
      {% endblock %}
</div>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <p class="m-0 text-muted">Copyright &copy; Clothatar Website 2017</p>
      </div>
    </footer>

    {% block javascript %}
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "clothatar/assets/js/vendor/jquery.min.js" %}"><\/script>')</script>
    <script src="{% static 'clothatar/dist/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'clothatar/assets/js/vendor/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'clothatar/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
</body>

</html>

webserver/clothatar/templates/clothatar/collection.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="wangjing" >

    <title>Shop Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Clothatar Powered</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="index.html">Home
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="collection.html">Collection<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Cloathatar match 95%</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-lg-6">
                <h6>Measurement Breakdown</h6>
                <p class="card-text">Size: AU 12<p>
                <p>Bust: 79 mm</p>
                <p>waist: 61 mm</p>
                <p>hips: 89</p>
              </div>
              <div class="col-lg-3">
                <div class="card mt-3"><SPAN class="image-frame">
                  <img class="icon icon-quick-view" src="img/female_3-bands_YYY.png" height="180px" width="60px" alt="">
                </span>
                </div>
              </div>
          </div>
        </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>
    <!-- Page Content -->
    <div class="container">
      <div class="row">

        <div class="col-lg-3">
          <div class="card mt-3"><SPAN class="image-frame">
            <a href="index.html" >
              <img class="icon icon-quick-view" src="img/p-1-1.jpg" height="200px" width="175px" alt="">
            </a>
          </span>
            <div class="card-body">
              <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Clothatar match 98%</button>
              <p>
              <h6 class="card-text">Suggested size: AU 12</h6>

              <p class="card-text">Atmos&Here<p>
              <h6>$24.99</h6>
              <p class="card-text">Elise Ruffle Wrap Dress</p>
              <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
              4.0 stars
            </div>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="card mt-3"><SPAN class="image-frame">
            <img class="icon icon-quick-view" src="img/prod2.jpg" height="200px" width="175px" alt="">
          </span>
            <div class="card-body">
              <h6 class="card-title">Clothatar match 85%</h6>
              <p class="card-text">Atmos&Here<p>
              <h6>$24.99</h6>
              <p class="card-text">Golden Flower Midi Dress</p>
              <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
              4.0 stars
            </div>
          </div>
        </div>      </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

<script>

$("#updateMatchData").click(function(){
  $.get("http://127.0.0.1:8000/clothmatch/query", function(data, status){
      console.log(status);
      document.getElementById("tasks_per_node_data").innerHTML = createNodeTableData(data);
      // $("#tasks_per_node_data").innerHTML = createNodeTableData(data);
    });
  });
</script>
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

webserver/clothatar/templates/clothatar/details.html
{% extends "clothatar/base.html" %}
{% load staticfiles %}
{% block content %}
        <div class="col-lg-8">

          <div class="card mt-4">
            <img class="card-img-top img-fluid" src="{% static pic_name %}" alt="">
            <div class="card-body">
              <h3 class="card-title">Product Name</h3>
              <h4>$24.99</h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>
              <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
              4.0 stars
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
              Product Reviews
            </div>
            <div class="card-body">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
              <small class="text-muted">Posted by Anonymous on 3/1/17</small>
              <hr>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
              <small class="text-muted">Posted by Anonymous on 3/1/17</small>
              <hr>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
              <small class="text-muted">Posted by Anonymous on 3/1/17</small>
              <hr>

              <a href="#" class="btn btn-success">Leave a Review</a>
            </div>
          </div>
          <!-- /.card -->

        </div>
        <!-- /.col-lg-9 -->

        <div class="col-lg-4">
        <div class="thumbnail">
          <br>
          <br>
          <a href="/w3images/nature.jpg">
            <img src="{% static 'img/atmos-here.jpg' %}" alt="Nature" style="width:30%">
          </a>
        </div>
        <div>
          <h4 class="my-4">{{ match_result.description }}</h4>
    	    <form action="">
            <div class="form-group">
            <select name="Size select">
	            <option value="">Pick a size ...</option>
	         	<option value="AU 6">"AU 6"</option>
            	<option value="AU 8">"AU 8"</option>
        			<option value="AU 10">"AU 10"</option>
        			<option value="AU 12">"AU 12"</option>
        			<option value="AU 14">"AU 14"</option>
            </select>
            </div>
          </form>
          {% if user_login == 1 %}
            <p>Clothatar Suggested Size : {{ match_result.suggest_size }}</p>
<!--            <button type="button" id="matchquery" class="btn btn-primary" onclick="document.getElementById('table_detail').style.display='block'">match detail</button>-->
            {% endif %}
		</div>

    {% if user_login == 1 %}
      <div class="table-responsive" id="table_detail" >
        <table class="table table-striped">
          <thead>
            <tr>
              <th>size</th>
              <th>matchpoint</th>
              <th>waist</th>
              <th>hips</th>
              <th>bust</th>

            </tr>
          </thead>
          <tbody id="matchpoint_result">
            {% for match_info in match_result.clothings %}
            <tr>
              <td>{{ match_info.size }}</td>
              <td>{{ match_info.match_point }}</td>
              <td>{{ match_info.waist }}</td>
              <td>{{ match_info.hips }}</td>
              <td>{{ match_info.bust }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      {% endif %}

    <button type="button" id="buy" class="btn btn-primary btn-block" >buy</button>
  </div>
       <!-- /.col-lg-3 -->

{% endblock %}

webserver/clothatar/templates/clothatar/list.html
{% extends "clothatar/base.html" %}
{% load staticfiles %}
{% block content %}

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Cloathatar match 95%</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-lg-6">
                <h6>Measurement Breakdown</h6>
                <p class="card-text">Size: AU 12<p>
                <p>Bust: 79 mm</p>
                <p>waist: 61 mm</p>
                <p>hips: 89</p>
              </div>
              <div class="col-lg-3">
                <div class="card mt-3"><SPAN class="image-frame">
                  <img class="icon icon-quick-view" src="{% static 'img/female_3-bands_YYY.png' %}" height="180px" width="60px" alt="">
                </span>
                </div>
              </div>
          </div>
        </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>
    <!-- Page Content -->
    <div class="container">
      <div class="row">

        {% for cloth in clothings %}
        <div class="col-lg-3">
          <div class="card mt-3"><SPAN class="image-frame">
            <a href="{% url "clothatar:cloth_detail" cloth.family_id %}" >
              <img class="icon icon-quick-view" src="{% static cloth.pic_name %}" height="200px" width="175px" alt="">
            </a>
          </span>
            <div class="card-body">
              {% if user_login == 1 %}
              <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Clothatar match {{ cloth.match_point }}%</button>
              <p>
              <h6 class="card-text">Suggested size: {{ cloth.size }}</h6>
              {% endif %}

              <p class="card-text">Atmos&Here<p>
              <h6>${{ cloth.price }} </h6>
              <p class="card-text">{{ cloth.description }}</p>
              <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
              4.0 stars
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
    <!-- /.container -->
{% endblock %}